sudo: required
services:
  - docker

before-install:
  - docker build -t cookiestest -f Dockerfile.dev .

script:
  - docker run cookiestest go test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-goweb"
  env: "docker-goweb-env"
  bucket-name: "elasticbeanstalk-eu-central-1-851258710947"
  bucket-path: "docker-goweb"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
